title: Can Static Be Collaborative?
author: DS@Swat
email: digitalscholarship@swarthmore.edu
description: > # this means to ignore newlines until "baseurl:"
  Keystone DH 2017: Collaborative Jekyll Workshop

github_username:  swat-ds

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

prose:
  rooturl: '_sass'
  media: 'assets'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Enter your title"
          value: ""
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "text"
          label: 'Author'
          placeholder: "post author"
      - name: "image_teaser"
        field:
          element: "text"
          value: "https://media3.giphy.com/media/3og0IFRM2W3Ylg4tIA/giphy.gif"
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish?"
          help: "Check the box when ready to publish"
          value: false
      - name: "googleDoc_id"
        field:
          element: "text"
          label: "googleDoc_id"
          placeholder: "example: 1xgOrIaWZYy_B_wpj_alKsMBMqDbPW2iwDjr4jKRHp80"
          help: "Enter string between document/d/ and /pub?"
          value: ""
      - name: "timeline_id"
        field:
          element: "text"
          label: "Timeline ID"
          placeholder: "example: 1uGjhA8mK551YwHW1wRF5sh1utOxDV73JfuJbILe2jOI"
          help: "If including a Timeline, enter the string of characters included in your Timelinejs project URL"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Blog"
              value: "blog"
            - name: "Essay"
              value: "essay"
            - name: "Comment"
              value: "value"
      - name: "modified"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
          
# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
